### ISSUE TITLE
Fehler bei MacOS-ARM64 Erkennung

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-lua-api-for-reaper#12]
https://github.com/Ultraschall/ultraschall-lua-api-for-reaper/blob/fe54351b6cdd4311175323b0093d6a3c7ee05509/ultraschall_api/Modules/ultraschall_functions_HelperFunctions_Module.lua#L1280

Diese Zeile liefert bei MacOS-ARM64 Rechnern false aus.
Grund: der Match-Befehl wird durch das "-" Zeichen im String aus dem Tritt gebracht.
Beispiel:
match("macOS") liefert: macOS
aber
match("macOS-) liefert: macO
das "-" ist also ein reservierter Charakter der hinten abschneidet.
Workaround für die Zeile:

if retval:match("OSX")~=nil or retval:match("macOS")~=nil then Os=true

**Comment by mespotine** [comment]
Thnx, wird gefixt für die nächste Release.

**Comment by mespotine** [comment]
Fixed
