### ISSUE TITLE
[BUG] Fehler beim Beenden von Reaper durch falschen Aufruf in ultraschall_EventManager.lua

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-lua-api-for-reaper#17]
Beim Schließen von REAPER wirft die API diesen Fehler:

...ns/ultraschall_api//Scripts/ultraschall_EventManager.lua:124: bad argument #3 to 'DeleteExtState' (boolean expected, got nil)

Die Zeile dort lautet (und die danach):

  reaper.DeleteExtState("ultraschall_eventmanager", "EventNames", EventNames, false)
  reaper.DeleteExtState("ultraschall_eventmanager", "EventIdentifier", EventNames, false)

Nach Doku erwartzet DeleteExtState aber nur zwei Parameter, der dritte muss boolean sein. Der EventNames Parameter ist also hier zu viel.

**Comment by mespotine** [comment]
Thnx. Gefixt in der nächsten Version.
