### ISSUE TITLE
GetUserInput breaks with commas

### ISSUE THREAD

**Issue by X-Raym** [Ultraschall/ultraschall-lua-api-for-reaper#4]
Hi,

GetUserInput breaks with ` ,`.

Here is a demo:

```lua
dofile(reaper.GetResourcePath().."/UserPlugins/ultraschall_api.lua")

local captions = {}
local defaults = {} 

for i = 1,7 do
    captions[i] = "A, B"
    defaults[i] = "A, B"
end

found,count,userInput = ultraschall.GetUserInputs("Bank Settings",captions,defaults,120)
ultraschall.ShowLastErrorMessage()
```

![image](https://user-images.githubusercontent.com/7224315/58472148-e66adb80-8145-11e9-957e-66855da3d49b.png)

Thx !

**Comment by X-Raym** [comment]
Ouch just saw this in the doc

```- no commas allowed!```

I was certain this ultrashall UserInput was meant for bypass this limitation, and used JS_ReaScriptAPI extension for that... Is it something which recently break or am I completely mistaken ?

Anyway, having commas available would be very nice. Especially since I started to put ultrashall UserInput into one of my script to solve this exact issue 😄

**Comment by mespotine** [comment]
fixed and lifted this limitation :)
