### ISSUE TITLE
[BUG] function ultraschall.CountParmLearn_FXStateChunk(FXStateChunk, fxid), returning 0

### ISSUE THREAD

**Issue by michaelsjackson** [Ultraschall/ultraschall-lua-api-for-reaper#6]
In a project with learned parameters it was counting 0 where it should count more. This is only a quick report to know something is not working properly in this function, on my computer.

In another project it was counting at least something.

**Comment by mespotine** [comment]
Is this still an issue or does it work now?

**Comment by michaelsjackson** [comment]
It is working perfectly. Closing, still did not try csv import yet, but hopefully at some point in future. Hopefully not too far. Then the full mapping fun can begin.
