### ISSUE TITLE
[BUG] ultraschall.GetStringFromClipboard_SWS nicht robust - REAPER Crash

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-lua-api-for-reaper#8]
Die Funktion

ultraschall.GetStringFromClipboard_SWS()

ist nicht robust gegenüber dem, was so im Clipboard liegen kann und führt reproduzierbar zu einem harten REAPER-Crash.
Vorgehen: ein beliebiges Item markieren, in die Zwischenablage kopieren mit `cmd`+`c` dann im Podcast-Menü die Action "Insert planned markers from clipboard" ausführen - Crash (MacOS).

Lösung: unklar, da im Hintergrund wohl eine SWS-Funktion verwendet wird. Check ob Clipboard zu groß, oder kein txt oder so etwas in der Richtung?

**Comment by mespotine** [comment]
Teste das mal mit ner neueren SWS-Beta und 
   
`Contents=reaper.CF_GetClipboard("")`

Sollte auf jeden Fall nen SWS-Bug sein.

**Comment by rstockm** [comment]
> Contents=reaper.CF_GetClipboard("")

An welcher Stelle/Datei sollte das wo rein?

**Comment by mespotine** [comment]
Einfach ultraschall.GetStringFromClipboard_SWS() mit reaper.CF_GetClipboard("") austauschen, aber vorher checken, ob ClipboardStrings>1024-Zeichen sauber gelesen und nicht vorher abgeschnitten werden.
