### ISSUE TITLE
Funktionsbezeichnung in Doku falsch

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-lua-api-for-reaper#9]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/3195116/99077997-ee2e7200-25bd-11eb-9421-93492efc7883.png">

Der Name der Funktion in der Doku scheint mir nicht aktuell zu sein...

**Comment by rstockm** [comment]
Die Dokumentation erscheint mir auch nicht stimmig:

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/3195116/99092994-35bef900-25d2-11eb-8cdd-8ef19a6d12d9.png">

**Comment by rstockm** [comment]
Und das hier (png)

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/3195116/99093317-9bab8080-25d2-11eb-86c2-1136a5d95ac3.png">

**Comment by mespotine** [comment]
Thnx. Gefixt in nächster Version.
